language: objective-c 

env:
    matrix:
        - PLATFORM="ios"
        - PLATFORM="android" ANDROID_VERSION="23"

before_install:
    - export ANDROID_HOME=$PWD/android-sdk-macosx
    - export ANDROID_SDK=$ANDROID_HOME
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

install:
    - npm install -g git://github.com/Akylas/titanium.git
    - npm install -g tishadow gulp ticalabash
    - npm install

    - titanium sdk install http://www.googledrive.com/host/0B3Yso-gHq5-UbVVHeGt5Q25GeFk --no-progress-bars

    - gulp 'install:android_sdk'

before_script:
    - gulp 'start:emulator'
    - gulp 'config:tiapp' --test

script: 
    - gulp 'test:calabash'
    - gulp 'test:jasmine'